version: "3.7"

services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - ./config/mongoInit.js:/docker-entrypoint-initdb.d/mongoInit.js:ro
  node:
    image: node
    container_name: node
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    command: bash -c "npm install && npm run dev"